config/routes.rb
Rails.application.routes.draw do

  root 'photos#index'

  resources :tags, :only => [:index] do
    post 'update_push', :on => :collection
    get 'update_get', :on => :collection
  end
  resources :members, :only => [:index]
  resources :photos, :only => [:index, :show] do
    get 'update_get', :on => :collection
    get 'photo_get', :on => :member
    get 'photo_get_rev', :on => :member
  end
  resources :statistics, :only=> [:index]
  resources :statistics2, :only=> [:index]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :photo
  belongs_to :member
  has_one :article, through: :photo
  
  scope :update_get, -> datetime { where('updated_at > ?', datetime)}
  scope :find_by_photo, -> photo_id { where('photo_id = ?', photo_id)}
  scope :find_by_member, -> member_id { where('member_id = ?', member_id)}
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  protect_from_forgery except: :update_push

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/update_get
  # GET /tags/update_get.json
  def update_get
    @datetime = params[:lastdt]
    if @datetime.blank?
      @tags = Tag.all
    else
      @tags = Tag.update_get @datetime
    end
  end
  
  # POST /tags/update_push
  # POST /tags/update_push.json
  # 想定するPOSTデータは以下
  # update_tags=[{"photo_id":1, "member_id":1, "push_mode":"add"}]
  def update_push
  
    # POSTのjsonを受け取る
    update_tags = JSON.parse(params["update_tags"])
    for update_tag in update_tags
      # 既存レコードを検索
      @tag = Tag.find_by_photo(update_tag["photo_id"]).find_by_member(update_tag["member_id"]).where("count > 0")
      if @tag.blank? && "add"==update_tag["mode"]
        # 存在しない場合かつカウントモードがaddの場合、レコードを追加する
        @tag = Tag.create :photo_id=>update_tag["photo_id"], :member_id=>update_tag["member_id"], :count=>1
      else
        # 存在した場合、カウントモードに応じてインクリメント/デクリメントする。
        # カウントモードが不正な場合何もしない
        if "add"==update_tag["mode"]
          @tag[0].increment!(:count)
        elsif "del"==update_tag["mode"] && @tag[0].count >= 0
          # マイナスにはしない
          @tag[0].decrement!(:count)
        end
      end
    end
    
    head 200
  end
private
  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:photo_id, :member_id, :mode)
    params.require(:update_tags)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Member</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.photo_id %></td>
        <td><%= tag.member_id %></td>
        <td><%= tag.count %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/update_get.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Member</th>
      <th>Count</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.photo_id %></td>
        <td><%= tag.member_id %></td>
        <td><%= tag.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>