config/routes.rb
Rails.application.routes.draw do

  root 'photos#index'

  resources :tags, :only => [:index] do
    post 'update_push', :on => :collection
    get 'update_get', :on => :collection
  end
  resources :members, :only => [:index]
  resources :photos, :only => [:index, :show] do
    get 'update_get', :on => :collection
    get 'photo_get', :on => :member
    get 'photo_get_rev', :on => :member
  end
  resources :statistics, :only=> [:index]
  resources :statistics2, :only=> [:index]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :tags, -> {where("count > ?", 0)}
  has_many :members, :through => :tags
  belongs_to :create_member, :class_name => "Member", :foreign_key => "create_member_id"
  belongs_to :article

  scope :has_tag_member_id, -> member_ids { joins(:tags).where("tags.member_id in (?)", member_ids).uniq}
  
  scope :update_get, -> datetime { where('created_at > ?', datetime)}
  
  def self.solo_only(member_id)
    
    # 単独メンバーのONLY検索
    target_photo_ids = Tag.select(:photo_id).
                           where("count > 0").
                           where(photo_id: Tag.where("count > 0").where(member_id: member_id).pluck(:photo_id)).
                           group(:photo_id).
                           having("count(photo_id) = 1")
          
    photos = Photo.where(id: target_photo_ids.uniq.pluck(:photo_id))
  end
  
  def self.and_only(photo_search)
    
    # まずは指定メンバー数のみのタグを持つPhotoのidを検索
    # この時点ではメンバーを絞っていない
    target_photo_ids = Tag.select(:photo_id).
                           where("count > ?", 0).
                           group(:photo_id).
                           having("count(photo_id) = ?", photo_search[:member_id].size)
        
    # 一旦抽出
    photo_ids = Photo.where(id: target_photo_ids.uniq.pluck(:photo_id)).pluck(:id)

          
    # 指定メンバーのタグを持つPhotoを抽出
    photo_search[:member_id].each do |mid|
      photo_ids = photo_ids & Tag.where(member_id: mid).where("count > 0").pluck(:photo_id)
    end
    
    Photo.where(id: photo_ids)
  end
  
  def self.and_in(photo_search)
    # まずは指定メンバー数以上のタグを持つPhotoのidを検索
    # この時点ではメンバーを絞っていない
    target_photo_ids = Tag.select(:photo_id).
                           where("count > ?", 0).
                           group(:photo_id).
                           having("count(photo_id) >= ?", photo_search[:member_id].size)
        
    # 一旦抽出
    photos = Photo.where(id: target_photo_ids.uniq.pluck(:photo_id))
          
    # 指定メンバーのタグを持つPhotoを抽出
    photo_search[:member_id].each do |mid|
      photos = photos.where(id: Tag.where(member_id: mid).where("count > 0").pluck(:photo_id))
    end
          
    photos
  end
  
  def self.or_only(photo_search)
    # solo_onlyの結果とand_onlyの結果のマージ
    ids = Array.new
    
    # 全メンバー分のsolo_onlyの結果から、Photo.idを取得しマージ
    photo_search[:member_id].each do |mid|
      ids.concat(Photo.solo_only(mid).pluck(:id))
    end
    
    # and_onlyの結果から、Photo.idを取得しマージ
    ids.concat(Photo.and_only(photo_search).pluck(:id))
    
    Photo.where(id: ids)
  end
  
  def self.or_in(photo_search)
    photos = Photo.has_tag_member_id(photo_search[:member_id]) if photo_search[:member_id].present?
  end
  
  def self.search(photo_search)

    photos = Photo.all

    if photo_search
      if photo_search[:nothingtag].present?
        not_target_ids = Photo.joins(:tags).uniq.pluck(:id)
        photos = Photo.where.not(id: not_target_ids)
        photo_search[:member_id] = nil
      else
        if photo_search[:only].present? && photo_search[:member_id].size == 1
          # 単独メンバーのONLY検索(単独なのでANDは無視できる)
          photos = Photo.solo_only(photo_search[:member_id])
          
        elsif photo_search[:and].present? && photo_search[:only].present?
          # 複数メンバーのAND, ONLY検索
          photos = Photo.and_only(photo_search)
        elsif photo_search[:and].present? && photo_search[:only].nil?
          # 複数メンバーのAND, IN検索
          photos = Photo.and_in(photo_search)
        elsif photo_search[:and].nil? && photo_search[:only].present?
          # 複数メンバーのOR,ONLY条件
          photos = Photo.or_only(photo_search)
        else
          # OR,IN検索(通常)
          photos = Photo.or_in(photo_search)
        end
      end
    end

    photos.order('created_at DESC').order('id DESC')

  end
  
  def previous
    Photo.order('created_at DESC').order('id desc').where('id < ?', id).first
  end

  def next
    Photo.order('created_at DESC').order('id DESC').where('id > ?', id).reverse.first
  end
  
  def previous_notag
    not_target_ids = Photo.includes(:tags).where(tags: {id: nil}).uniq.pluck(:id)
    Photo.order('created_at DESC').order('id DESC').where(id: not_target_ids).where('id < ?', id).first
  end

  def next_notag
    not_target_ids = Photo.includes(:tags).where(tags: {id: nil}).uniq.pluck(:id)
    Photo.order('created_at DESC').order('id DESC').where(id: not_target_ids).where('id > ?', id).reverse.first
  end
end

app/controllers/photos_controller.rb
require "mini_magick"

class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :photo_get, :photo_get, :photo_get_rev]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.search(params[:photo_search]).page(params[:page]).per(20)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/update_get
  # GET /photos/update_get.json
  def update_get
    @datetime = params[:lastdt]
    if @datetime.blank?
      @photos = Photo.all
    else
      @photos = Photo.update_get @datetime
    end
  end
  
  # GET /photo/:id/photo_get
  # GET /photo/:id/photo_get.json
  def photo_get
    send_file SanbeeBlogPhoto::Application.config.img_path_root + @photo.path, :disposition => "inline", :status => "200"
  end

  # GET /photo/:id/photo_get_rev
  # GET /photo/:id/photo_get_rev.json
  def photo_get_rev
    path = SanbeeBlogPhoto::Application.config.img_path_root + @photo.path
    img = MiniMagick::Image.open(path)
    flop_img = img.flop
    
    send_data flop_img.to_blob, :disposition => "inline", :filename => @photo.path, :type => "image/jpeg", :status => "200"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:path, :create_member_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper

  def search_panel
    
    searchMemberMap = {}
    if params[:photo_search].present? && params[:photo_search][:member_id].present?
      params[:photo_search][:member_id].each do |m|
        searchMemberMap[m.to_s] = m
      end
    end
    p searchMemberMap

    unitMap = {}
    unitMap[2] = "アメフラっシ"
    unitMap[7] = "その他"
    unitMap[4] = "3Bjr"

    content_tag :div, :class=>"panel-group", :id=>"unit" do
      unitMap.each do |id, unit|
        concat ( content_tag :div, :class=>"panel panel-default" do
          concat ( content_tag :div, :class=>"panel-heading" do
            concat ( content_tag :h4, :class=>"panel-title" do
              concat ( content_tag :a, :data=>{:toggle=>"collapse", :parent=>"#unit"}, :href=>"#area#{id}" do
                concat unit
              end)
            end)
          end)
        end)
        concat ( content_tag :div, :id=>"area#{id}", :class=>"panel-body collapse" do
          concat search_buttons id, searchMemberMap
        end)
      end
      concat ( content_tag :div, :class=>"panel panel-default" do
        concat ( content_tag :div, :class=>"panel-heading" do
          concat ( content_tag :h4, :class=>"panel-title" do
            concat ( content_tag :a, :data=>{:toggle=>"collapse", :parent=>"#unit"}, :href=>"#area0" do
              concat "タグ無し(他の条件より優先します)"
            end)
          end)
        end)
      end)
      concat ( content_tag :div, :id=>"area0", :class=>"panel-body collapse" do
        concat ( content_tag :div, :class=>"btn-group", :data=>{:toggle=>"buttons"} do
          inActive = "active" if params[:photo_search].present? && params[:photo_search][:nothingtag].present?
          concat ( content_tag :label, :class=>"btn btn-lg btn-default member-button #{inActive}", :data=>{:member_id=>"0"} do
            concat ( content_tag :input, :type=>"checkbox", :autocomplete=>"off", :name=>"photo_search[nothingtag]", :value=>"0" do
              concat "タグ無し"
            end)
          end)
        end)
      end)
    end
  end

  def search_buttons(unit_id, searchMemberMap)
    content_tag :div, :class=>"btn-group", :data=>{:toggle=>"buttons"} do
      Member.where(unit_id: unit_id).each do |m|
        inActive = "active" if searchMemberMap[m.id.to_s].present?
        concat ( content_tag :label, :class=>"btn btn-lg btn-default member-button #{inActive}", :data=>{:member_id=>m.id} do
          concat ( content_tag :input, :type=>"checkbox", :autocomplete=>"off", :name=>"photo_search[member_id][]", :value=>m.id do
            m.name
          end)
        end)
      end
    end
  end

  def tag_panel(photo)

    unitMap = {}
    unitMap[2] = "アメフラっシ"
    unitMap[7] = "その他"
    unitMap[4] = "3Bjr"

    content_tag :div, :class=>"panel-group", :id=>"tag" do
      unitMap.each do |id, unit|
        concat ( content_tag :div, :class=>"panel panel-default" do
          concat ( content_tag :div, :class=>"panel-heading" do
            concat ( content_tag :h4, :class=>"panel-title" do
              concat ( content_tag :a, :data=>{:toggle=>"collapse", :parent=>"#tag"}, :href=>"#area#{id}" do
                concat unit
              end)
            end)
          end)
        end)
        collapseState = "collapse"
        if id == 2 || id == 7
          collapseState = "collapse in"
        end
        concat ( content_tag :div, :id=>"area#{id}", :class=>"panel-body #{collapseState}" do
          concat tag_buttons @photo, id
        end)
      end
    end
  end

  def tag_buttons(photo, unit_id)

    tags = {}
    photo.tags.each do |t|
      tags[t.member_id] = t
    end

    content_tag :div, :class=>"btn-group", :data=>{:toggle=>"buttons"} do
      Member.where(unit_id: unit_id).each do |m|
        if !tags[m.id].nil? && !tags[m.id].count.nil? && tags[m.id].count > 0
          concat ( content_tag :label, :class=>"btn btn-lg btn-default tag-button active", :data=>{:photo_id =>photo.id, :member_id=>m.id} do
            concat ( content_tag :input, :type=>"checkbox", :autocomplete=>"off", :checked=>true do
              m.name
            end)
          end)
        else
          concat ( content_tag :label, :class=>"btn btn-lg btn-default tag-button", :data=>{:photo_id =>photo.id, :member_id=>m.id} do
            concat ( content_tag :input, :type=>"checkbox", :autocomplete=>"off" do
              m.name
            end)
          end)
        end
      end
    end
  end
end

app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :class => "form-horizontal photo" } do |f| %>

  <% if @photo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :path, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :path, :class => 'form-control' %>
    </div>
    <%=f.error_span(:path) %>
  </div>
  <div class="form-group">
    <%= f.label :create_member_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :create_member_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:create_member_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                photos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/photos/_photo.html.erb
<div class="col-xs-6 col-sm-4 col-md-2 photo">
  <% isTaged = "taged" if photo.tags.present? %>
  <%= link_to image_tag(photo_get_photo_path(photo), :class => "img-thumbnail img-responsive #{isTaged}"),
              photo_path(photo), :class => 'thumbnail' %>
</div>

app/views/photos/edit.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<%- model_class = Photo -%>
<br />
<br />
<%= form_tag photos_path, :method=>"get", :id=>"search-form" do %>
<div class="panel-group" id="search">
  <div class="panel panel-default">
  	<div class="panel-heading">
  	  <h3 class="panel-title">
  	  	<a data-toggle="collapse", data-parent="#search" href="#members">
  	  	  検索
  	  	</a>
  	  </h3>
  	</div>
  	<div class="panel-body collapse" id="members">
  	  <%= button_tag "検索する", :type=>"button", :class=>"btn btn-lg btn-default search-button" %>
  	  <%= search_panel %>
  	  <div class="panel-group" id="#complex">
  	    <div class="panel panel-default">
  	  	  <div class="panel-heading">
  	  	    <h4 class="panel-title">
  	  	  	  <a data-toggle="collapse", data-parent="#complex", href="#areaComplex">複雑な検索条件</a>
  	  	    </h4>
  	  	  </div>	
  	    </div>
  	    <div class="panel-body collapse" id="areaComplex">
  	      <div>
  	      	<% if params[:photo_search].present? && params[:photo_search][:and].present? %>
  	          <input type="checkbox" name="photo_search[and]" checked data-on="AND検索" data-off="OR検索" data-toggle="toggle" data-size="large" data-width="130">
  	        <% else %>
  	          <input type="checkbox" name="photo_search[and]" data-on="AND検索" data-off="OR検索" data-toggle="toggle" data-size="large" data-width="130">
  	        <% end %>
  	        AND検索: AとBが載っている画像
  	        OR検索: AかBが載っている画像
          </div>
          <br />
          <div>
          	<% if params[:photo_search].present? && params[:photo_search][:only].present? %>
  	          <input type="checkbox" checked name="photo_search[only]" data-on="ONLY検索" data-off="IN検索" data-toggle="toggle" data-size="large" data-width="130">
  	        <% else %>
  	          <input type="checkbox" name="photo_search[only]" data-on="ONLY検索" data-off="IN検索" data-toggle="toggle" data-size="large" data-width="130">
  	        <% end %>
  	        ONLY検索: AとBだけが載っている画像
  	        IN検索: AとBと他の誰かが載っていても良い画像
          </div>
  	    </div>
  	  </div> 
      <%= button_tag "検索する", :type=>"button", :class=>"btn btn-lg btn-default search-button" %>
    </div>
  </div>
</div>
<% end %>
<%= paginate(@photos) %>
<div id="photos" class="container-fluid">
  <div class="row">
    <%= render @photos %>
  </div>
</div>

app/views/photos/index.js.erb
$("#id").append("<div class="row"><%= escape_javascript(render(@photos)) %></div>");

app/views/photos/show.html.erb
<%- model_class = Photo -%>
<dl class="dl-horizontal">
  <dt></dt>
  <dd>
  	<%= image_tag photo_get_photo_path(@photo), :class => 'img-responsive', :id => 'photo'%>
  	(画像タップで左右反転)
  </dd>
  <dt><strong>ブログへリンク</strong></dt>
  <dd>
  	<% if @photo.article.present? %>
  	  <%= link_to @photo.article.title, @photo.article.url, :target=>["_blank"] %>
  	<% else %>
  	  <%= link_to @photo.url, @photo.url, :target=>["_blank"] %>
  	<% end %>
  </dd>
  <dt><strong>投稿者</strong></dt>
  <dd>
  	<% if @photo.article.present? && @photo.article.member.present? %>
  	  <%= @photo.article.member.name %>
  	<% end %>
  </dd>
  <dt><strong>誰が写ってる？</strong></dt>
  <dd>
  	<%= tag_panel @photo %>
  </dd>
</dl>

<div class="row">
  <div class="col-md-4">
  	<% if @photo.previous.present? %>
      <%= link_to "前の画像へ", photo_path(@photo.previous), :class => 'btn btn-default btn-lg' %>
    <% end %>
  	<% if @photo.previous_notag.present? %>
  	  <%= link_to "前のタグづけしていない画像へ", photo_path(@photo.previous_notag), :class => 'btn btn-default btn-lg' %>
  	<% end %>
  </div>
  <div class="col-md-4 ">
  	<div class="btn-center">
      <%= link_to "前の画面へ戻る", "#", :class => 'btn btn-default btn-lg back-button'  %>
      <%= link_to "一覧へ戻る", photos_path, :class => 'btn btn-default btn-lg'  %>
    </div>
  </div>
  <div class="col-md-4">
  	<% if @photo.next_notag.present? %>
  	  <%= link_to "次のタグ付けしていない画像へ", photo_path(@photo.next_notag), :class => 'btn btn-default btn-lg' %>
  	<% end %>
  	<% if @photo.next.present? %>
  	  <%= link_to "次の画像へ", photo_path(@photo.next), :class => 'btn btn-default btn-lg' %>
  	<% end %>
  </div>
</div>

app/views/photos/update_get.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>Create member</th>
      <th>Photo</th>
      <th>Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.path %></td>
        <td><%= photo.create_member.name %></td>
        <td><%= image_tag photo_get_photo_path(photo) %></td>
        <td>
          <% photo.tags.each do |t| %>
            <div class="tag">
              <%= t.member.name %>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>